export const ADMIN_COURSES_REQUEST = 'ADMIN_COURSES_REQUEST'
export const ADMIN_COURSES_SUCCESS = 'ADMIN_COURSES_SUCCESS'
export const ADMIN_COURSES_FAIL = 'ADMIN_COURSES_FAIL'

export const ALL_COURSES_REQUEST = 'ALL_COURSES_REQUEST'
export const ALL_COURSES_SUCCESS = 'ALL_COURSES_SUCCESS'
export const ALL_COURSES_FAIL = 'ALL_COURSES_FAIL'

export const NEW_COURSE_REQUEST = 'NEW_COURSE_REQUEST'
export const NEW_COURSE_SUCCESS = 'NEW_COURSE_SUCCESS'
export const NEW_COURSE_RESET = 'NEW_COURSE_RESET'
export const NEW_COURSE_FAIL = 'NEW_COURSE_FAIL'

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_RESET = 'DELETE_COURSE_RESET'
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL'

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'
export const UPDATE_COURSE_RESET = 'UPDATE_COURSE_RESET'
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL'

export const NEW_FEEDBACK_REQUEST = 'NEW_FEEDBACK_REQUEST'
export const NEW_FEEDBACK_SUCCESS = 'NEW_FEEDBACK_SUCCESS'
export const NEW_FEEDBACK_RESET = 'NEW_FEEDBACK_RESET'
export const NEW_FEEDBACK_FAIL = 'NEW_FEEDBACK_FAIL'

export const GET_FEEDBACKS_REQUEST = 'GET_FEEDBACKS_REQUEST'
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS'
export const GET_FEEDBACKS_FAIL = 'GET_FEEDBACKS_FAIL'

export const DELETE_FEEDBACK_REQUEST = 'DELETE_FEEDBACK_REQUEST'
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS'
export const DELETE_FEEDBACK_RESET = 'DELETE_FEEDBACK_RESET'
export const DELETE_FEEDBACK_FAIL = 'DELETE_FEEDBACK_FAIL'

export const GET_ADMIN_FEEDBACKS_REQUEST = 'GET_FEEDBACKS_REQUEST'
export const GET_ADMIN_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS'
export const GET_ADMIN_FEEDBACKS_FAIL = 'GET_FEEDBACKS_FAIL'

export const DELETE_ADMIN_FEEDBACK_REQUEST = 'DELETE_FEEDBACK_REQUEST'
export const DELETE_ADMIN_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS'
export const DELETE_ADMIN_FEEDBACK_RESET = 'DELETE_FEEDBACK_RESET'
export const DELETE_ADMIN_FEEDBACK_FAIL = 'DELETE_FEEDBACK_FAIL'


export const MY_COURSES_REQUEST = 'MY_COURSES_REQUEST'
export const MY_COURSES_SUCCESS = 'MY_COURSES_SUCCESS'
export const MY_COURSES_FAIL = 'MY_COURSES_FAIL'

export const MY_ENROLL_COURSES_REQUEST = 'MY_COURSES_REQUEST'
export const MY_ENROLL_COURSES_SUCCESS = 'MY_COURSES_SUCCESS'
export const MY_ENROLL_COURSES_FAIL = 'MY_COURSES_FAIL'

export const ENROLL_COURSES_REQUEST = 'ENROLL_COURSES_REQUEST'
export const ENROLL_COURSES_SUCCESS = 'ENROLL_COURSES_SUCCESS'
export const ENROLL_COURSES_FAIL = 'ENROLL_COURSES_FAIL'


export const NEW_SECTION_REQUEST = 'NEW_SECTION_REQUEST'
export const NEW_SECTION_SUCCESS = 'NEW_SECTION_SUCCESS'
export const NEW_SECTION_RESET = 'NEW_SECTION_RESET'
export const NEW_SECTION_FAIL = 'NEW_SECTION_FAIL'

export const GET_SECTIONS_REQUEST = 'GET_SECTIONS_REQUEST'
export const GET_SECTIONS_SUCCESS = 'GET_SECTIONS_SUCCESS'
export const GET_SECTIONS_FAIL = 'GET_SECTIONS_FAIL'

export const DELETE_SECTION_REQUEST = 'DELETE_SECTION_REQUEST'
export const DELETE_SECTION_SUCCESS = 'DELETE_SECTION_SUCCESS'
export const DELETE_SECTION_RESET = 'DELETE_SECTION_RESET'
export const DELETE_SECTION_FAIL = 'DELETE_SECTION_FAIL'

export const UPDATE_SECTION_REQUEST = 'UPDATE_SECTION_REQUEST'
export const UPDATE_SECTION_SUCCESS = 'UPDATE_SECTION_SUCCESS'
export const UPDATE_SECTION_RESET = 'UPDATE_SECTION_RESET'
export const UPDATE_SECTION_FAIL = 'UPDATE_SECTION_FAIL'

export const NEW_LECTURE_REQUEST = 'NEW_LECTURE_REQUEST'
export const NEW_LECTURE_SUCCESS = 'NEW_LECTURE_SUCCESS'
export const NEW_LECTURE_RESET = 'NEW_LECTURE_RESET'
export const NEW_LECTURE_FAIL = 'NEW_LECTURE_FAIL'

export const GET_LECTURES_REQUEST = 'GET_LECTURES_REQUEST'
export const GET_LECTURES_SUCCESS = 'GET_LECTURES_SUCCESS'
export const GET_LECTURES_FAIL = 'GET_LECTURES_FAIL'

export const DELETE_LECTURE_REQUEST = 'DELETE_LECTURE_REQUEST'
export const DELETE_LECTURE_SUCCESS = 'DELETE_LECTURE_SUCCESS'
export const DELETE_LECTURE_RESET = 'DELETE_LECTURE_RESET'
export const DELETE_LECTURE_FAIL = 'DELETE_LECTURE_FAIL'

export const UPDATE_LECTURE_REQUEST = 'UPDATE_LECTURE_REQUEST'
export const UPDATE_LECTURE_SUCCESS = 'UPDATE_LECTURE_SUCCESS'
export const UPDATE_LECTURE_RESET = 'UPDATE_LECTURE_RESET'
export const UPDATE_LECTURE_FAIL = 'UPDATE_LECTURE_FAIL'

export const NEW_DISCUSSION_REQUEST = 'NEW_DISCUSSION_REQUEST'
export const NEW_DISCUSSION_SUCCESS = 'NEW_DISCUSSION_SUCCESS'
export const NEW_DISCUSSION_RESET = 'NEW_DISCUSSION_RESET'
export const NEW_DISCUSSION_FAIL = 'NEW_DISCUSSION_FAIL'

export const GET_DISCUSSIONS_REQUEST = 'GET_DISCUSSIONS_REQUEST'
export const GET_DISCUSSIONS_SUCCESS = 'GET_DISCUSSIONS_SUCCESS'
export const GET_DISCUSSIONS_FAIL = 'GET_DISCUSSIONS_FAIL'

export const DELETE_DISCUSSION_REQUEST = 'DELETE_DISCUSSION_REQUEST'
export const DELETE_DISCUSSION_SUCCESS = 'DELETE_DISCUSSION_SUCCESS'
export const DELETE_DISCUSSION_RESET = 'DELETE_DISCUSSION_RESET'
export const DELETE_DISCUSSION_FAIL = 'DELETE_DISCUSSION_FAIL'

export const UPDATE_DISCUSSION_REQUEST = 'UPDATE_DISCUSSION_REQUEST'
export const UPDATE_DISCUSSION_SUCCESS = 'UPDATE_DISCUSSION_SUCCESS'
export const UPDATE_DISCUSSION_RESET = 'UPDATE_DISCUSSION_RESET'
export const UPDATE_DISCUSSION_FAIL = 'UPDATE_DISCUSSION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'